### ISSUE TITLE
dyId: Symbol not found: OBJC_CLASS$__TtCs12_SwiftObject - IntuneMAMSwift.framework

### ISSUE THREAD

**Issue by slnali** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#48]
dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /Users/_/Library/Developer/CoreSimulator/Devices/18FE6DA6-C140-41AB-8B8F-E4CB9CB8A648/data/Containers/Bundle/Application/5C108836-4EF8-4EA7-8AC3-48C315D06069/chatr.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift
  Expected in: /Users/_/Library/Developer/Toolchains/swift-5.0-RELEASE.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib

in /Users/_/Library/Developer/CoreSimulator/Devices/18FE6DA6-C140-41AB-8B8F-E4CB9CB8A648/data/Containers/Bundle/Application/5C108836-4EF8-4EA7-8AC3-48C315D06069/chatr.app/Frameworks/IntuneMAMSwift.framework/IntuneMAMSwift

I get a successful build of the project but as the simulator starts to run the app I get above error. iOS 13, Intune (11.2.0).

**Comment by Kyle-Reis** [comment]
Hey @slnali, it sounds like you may be trying to build with Xcode 11. Xcode 11 is not supported with the current version of the SDK. We are working on releasing an update to our SDK, and will in-turn update the sample repo as well. For now, the recommendation is to build with Xcode 10.

**Comment by slnali** [comment]
Thanks Kyle that worked, app is running now.

**Comment by slnali** [comment]
Closed
