### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by curia-damiano** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#51]
Hi,
I have downloaded the source codes of the app; it compiles successfully with Xcode 11.7, released just yesterday.
I deploy the app to my iPhone.
When I press the login button, I immediately get this error message: "Error Authenticating. There was an error while logging you into your account. Please check your log in credentials and try again.".
But I have never been presented a login page!

**Comment by curia-damiano** [comment]
Ok, I see from the Xcode diagnostics that I result logged in with another account for another demo:

Current file index 0
2020-09-02 18:46:39.167733+0200 chatr[886:235902] Unbalanced calls to begin/end appearance transitions for <CMARPolicyViewController: 0x14b80c600>.
Enrollment result for identity damiano@DemoXXXX.onmicrosoft.com with status code IntuneMAMEnrollmentStatusCode
Debug message: Optional("The operation could not be completed because the user is not licensed for MAM.")

How can I log out from the previous login on my iPhone?

**Comment by Kyle-Reis** [comment]
Hey @curia-damiano, yes it sounds like the Intune SDK is detecting that an account was already enrolled in another app that was signed by the same publisher. Are you able to run that app again to log out/unenroll the account? Some other options:
Uninstall all of the apps on the device that were signed by the same publisher before attempting to install/run this sample.
If it is just a test device, you can reset it in the device settings (General -> Reset -> Erase all contents and settings) to clear the keychain.

**Comment by curia-damiano** [comment]
Hi @Kyle-Reis , you can close this issue, thanks!

**Comment by nevertheless75** [comment]
I'm running into the same issue. How did you solve it eventually? My user was not used for any other Intune managed app before. I build the app once and tried to login before the user had assigned a license. Do you think that causes the issue? Deleting the app and build from scratch does not help.

**Comment by Kyle-Reis** [comment]
Hi @nevertheless75, Are you still seeing this issue? If so, do you see a credential prompt when pressing the login button, or do you immediately get an error message?

**Comment by surajindoqubix** [comment]
Hi @Kyle-Reis ,

Getting the same issue. Yes credential prompt is happening and user is getting successully logged in ,but delegate callback is giving error instead of success. This is the code that I am using.

class EnrollmentDelegateClass: NSObject, IntuneMAMEnrollmentDelegate {

    var presentingViewController: UIViewController?

    override init() {
        super.init()
        self.presentingViewController = nil
    }

    init(viewController: UIViewController) {
        super.init()
        self.presentingViewController = viewController
    }

    func enrollmentRequest(with status: IntuneMAMEnrollmentStatus) {
        if status.didSucceed {
            LoggingHelper.printInfo("Login Successful")
            AppDelegate.appDelegate.navigateToHomeScreen()
        } else if IntuneMAMEnrollmentStatusCode.loginCanceled != status.statusCode {
            LoggingHelper.printError("Login Failed \(String(describing: status.errorString))")
        }
    }

    func unenrollRequest(with status: IntuneMAMEnrollmentStatus) {
    }
}


class ViewController: UIViewController {
    
    @IBOutlet weak var userName: UILabel!

    override func viewDidLoad() {
        super.viewDidLoad()
        let enrollmentDelegate = EnrollmentDelegateClass.init(viewController: self)
        IntuneMAMEnrollmentManager.instance().delegate = enrollmentDelegate
        IntuneMAMEnrollmentManager.instance().loginAndEnrollAccount(nil)        
    }

}


**Error :** "The operation could not be completed because the user is not licensed for MAM."

**Comment by Kyle-Reis** [comment]
Hi @surajindoqubix, has the user been [assigned an Intune license](https://docs.microsoft.com/mem/intune/fundamentals/licenses-assign)?

**Comment by surajindoqubix** [comment]
yes @Kyle-Reis  indeed the user is assigned an intune license. I am able to achieve proper login when tried on sample application provided at https://docs.microsoft.com/en-us/samples/azure-samples/ms-identity-mobile-apple-swift-objc/ios-ms-graph-api/ for MSAL authentication.
