### ISSUE TITLE
Chatr won't compile with new IntuneMAMSwift.framework: "error: no such module 'System'"

### ISSUE THREAD

**Issue by slmille4** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#53]
I'm trying to compile with the new MAM framework, but I get the following errors. I get similar errors in my own app:

.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwiftStub.framework/Modules/IntuneMAMSwiftStub.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:9:8: error: no such module 'System'
import System
       ^
.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwift.framework/Modules/IntuneMAMSwift.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:7:8: error: failed to load module 'IntuneMAMSwiftStub'
import IntuneMAMSwiftStub
       ^
.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwiftStub.framework/Modules/IntuneMAMSwiftStub.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:9:8: error: no such module 'System'
import System
       ^
<unknown>:0: error: failed to load module 'IntuneMAMSwift'
.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwiftStub.framework/Modules/IntuneMAMSwiftStub.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:9:8: error: no such module 'System'
import System
       ^
.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwift.framework/Modules/IntuneMAMSwift.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:7:8: error: failed to load module 'IntuneMAMSwiftStub'
import IntuneMAMSwiftStub
       ^
.../Chatr-Sample-Intune-iOS-App-master/IntuneMAMSwiftStub.framework/Modules/IntuneMAMSwiftStub.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:9:8: error: no such module 'System'
import System
       ^
Command MergeSwiftModule failed with a nonzero exit code

**Comment by Kyle-Reis** [comment]
Hi @slmille4, are you trying to link version 13.0.0 of the Intune SDK? Which version of Xcode are you building with?

**Comment by slmille4** [comment]
never mind, updating Xcode fixed this
