### ISSUE TITLE
Building for ios simulator, but the linked and embedded framework was built for ios + ios simulator

### ISSUE THREAD

**Issue by slmille4** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#54]
In the latest version of Xcode, I started getting the following errors in my app and the Chatr sample app:
<img width="584" alt="Screen Shot 2020-12-18 at 12 43 07 PM" src="https://user-images.githubusercontent.com/6100072/102644515-f3d42600-412e-11eb-91f5-ebfab2eb2b8d.png">

**Comment by slmille4** [comment]
workaround here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/130

**Comment by Kyle-Reis** [comment]
@slmille4 - This issue should be addressed with the latest updates to the sample app.
