### ISSUE TITLE
Failed to build module 'IntuneMAMSwift' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

### ISSUE THREAD

**Issue by abuzarin93** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#55]
XCODE 12.2 . how to solve this one . already try : Build Libraries for Distribution option to Yes,  "Validate Workspace" in you project's build settings to Yes also not working. 

error 1
Unable to load standard library for target 'arm64-apple-ios10.0'

error2
Showing Recent Messages
PolicyDelegate.swift:5:8: Failed to build module 'IntuneMAMSwift' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

****
<img width="494" alt="Screenshot 2021-01-22 at 17 24 00" src="https://user-images.githubusercontent.com/10832233/105472697-37debb80-5cd7-11eb-886f-49c55d2bd333.png">

**Comment by Kyle-Reis** [comment]
Hi @abuzarin93, does this issue reproduce with the latest changes to the sample?

**Comment by abuzarin93** [comment]
now its fine!. i can run it now without error after fetch latest 26jan code. thanks Kyle-Reis.
