### ISSUE TITLE
libIntuneMAMSwift not found

### ISSUE THREAD

**Issue by gambarle** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#56]
I'm running an ionic app with Cordova iOS, and trying to incorporate Intune MAM SDK into this app.

I have successfully added the Intune MAM SDK into XCode, and have build a plugin for my app to call the 'loginAndEnrollAccount' Objective C method.

When I '#import <libIntuneMAMSwift>' I get ''IntuneMAMSwift' file not found, message in XCode.

I have added Framework Search Paths for both debug and release to the 'libIntuneMAMSwift' and 'IntuneMAMSwiftStub' files, with no success.

I realise it is a stretch to ask for support in this matter, but any help or knowledge, is greatly appreciated.

**Comment by Kyle-Reis** [comment]
Hi @gambarle - Are you linking to the [latest version](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune SDK, which uses xcframeworks?

**Comment by gambarle** [comment]
@Kyle-Reis Yes I am using 'ms-intune-app-sdk-ios-14.1.3' (with XCode 12.4) and I have tried both 'IntuneMAMSwift.xcframework' and 'libIntuneMAMSwift.xcframework'

**Comment by Kyle-Reis** [comment]
Thanks @gambarle. With xcframeworks, you shouldn't need to manually set up header search paths. Xcode should handle this automatically :) Could you share what your import statements look like?

**Comment by gambarle** [comment]
@Kyle-Reis, for import statements i've used `#import <libIntuneMAMSwift>` and `#import <IntuneMAMSwift>`
I understand from the Microsoft documentation, that I need to call:
`loginAndEnrollAccount method on the IntuneMAMEnrollmentManager instance`
I'm not really sure how to instantiate the `IntuneMAMEnrollmentManager`, but I figure that I have to #import the Intune SDK, for my plugin to see the Intune framework.

**Comment by Kyle-Reis** [comment]
Hey @gambarle, in Objective-C, you actually need to import the specific header file that contains the APIs you want to reference. You can see all of the Intune SDKs public header files here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/tree/master/IntuneMAMSwift.xcframework/ios-arm64/IntuneMAMSwift.framework/Headers

If linking to IntuneMAMSwift.xcframework, you can import a particular header like this: #import <IntuneMAMSwift/IntuneMAM.h> IntuneMAM.h just contains imports for all of the other framework headers, and will make all of the SDKs APIs available within that file. You can also import a specific header to only pull in what you actually need using an import statement in this format: #import <IntuneMAMSwift/[HeaderName].h>

If using libIntuneMAMSwift.h, you can import headers like this: #import "IntuneMAM.h"

**Comment by gambarle** [comment]
@Kyle-Reis you are a saviour, thank you so much for your input.

I am currently using `libIntuneMAMSwift.xcframework` and I am able to #import <IntuneMAM.h> and `#import <IntuneMAMEnrollmentManager.h>` and now I can use ` [[IntuneMAMEnrollmentManager instance] loginAndEnrollAccount:user]`
I just need to find out how exactly to handle the call with a call back.
Do you know of any Objective-C code examples, for the `loginAndEnrollAccount` procedure?
Thx again.

**Comment by Kyle-Reis** [comment]
Hi @gambarle, we have begun work on an Objective-C sample, but it is still really early on and there is no real ETA on it yet. The enrollment delegate code in [EnrollmentDelegate.swift] https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/blob/master/chatr/EnrollmentDelegate.swift  and [AppDelegate.swift](https://github.com/msintuneappsdk/Chatr-Sample-Intune-iOS-App/blob/master/chatr/AppDelegate.swift) should be pretty straightforward to translate into Objective-C.

**Comment by Kyle-Reis** [comment]
This section of our documentation and the following section which contains sample enrollment delegate method implementations may also help:
https://docs.microsoft.com/mem/intune/developer/app-sdk-ios#status-result-and-debug-notifications

**Comment by gambarle** [comment]
Thanks again, I'll close the issue

**Comment by mahavrani** [comment]
Im using swift option 2 static library approach as dynamic library im facing crash.Im unable to import for swift .Im using libIntuneMAMSwift.xcframework.Please suggest
