### ISSUE TITLE
Could integrate Intune SDK without Microsoft Authentication Library?

### ISSUE THREAD

**Issue by ntminhdn** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#57]
I read from README: "It uses the Microsoft Authentication Library to authenticate users". But I don't find any code like "client_id" or "redirect_uri". Why does this sample work without MSAL config?

**Comment by abasore** [comment]
HI @ntminhdn, this Chatr app uses loginAndEnrollAccount in the LoginPage.swift. This [doc ](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-do-not-use-adal-or-msal) describes how the SDK will attempt to handle the authentication. MSAL settings will still need to be configured in the IntuneMAMSettings portion of the info.plist as described [here](SDK will then try to enroll the app with the Intune MAM service on behalf of the supplied user account). Alternatively, apps that already authenticate with MSAL should use registerAndEnrollAccount as described [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios#apps-that-already-use-adal-or-msal). This [Wagr ObjC example app](https://github.com/msintuneappsdk/wagr/blob/main/Wagr/Application/Login/LoginViewController.m) shows an example of using registerAndEnrollAccount.

**Comment by ntminhdn** [comment]
Thank you. I got it. @abasore
