### ISSUE TITLE
MAM policy issues

### ISSUE THREAD

**Issue by VictorKimbi** [msintuneappsdk/Chatr-Sample-Intune-iOS-App#58]
I am facing this issue 'The account is licensed for Intune but is not targeted with MAM policy' when IntuneMAMEnrollment function is called, can anyone please can someone please explain to me what could be the issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue since a duplicate one was filed here: https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/281
